In [1]:
from __future__ import print_function, division
from collections import defaultdict, OrderedDict
import gzip
import pickle
import json

import uproot
%matplotlib nbagg
import matplotlib.pyplot as plt
import numpy as np

from fnal_column_analysis_tools import hist
from fnal_column_analysis_tools.hist import plot

In [3]:
a = np.arange(10)

In [4]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
np.clip(a, 1, 8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

In [7]:
np.clip(a, 2, 8)

array([2, 2, 2, 3, 4, 5, 6, 7, 8, 8])

In [8]:
np.clip(a,3,5)

array([3, 3, 3, 3, 4, 5, 5, 5, 5, 5])

In [9]:
indices = []

In [10]:
indices.append(np.clip(a,2,4))

In [11]:
print(indices)

[array([2, 2, 2, 3, 4, 4, 4, 4, 4, 4])]


In [12]:
np.searchsorted([1,2,3,4,5], 3)

2

In [13]:
np.clip(a, 3, 6, out=a)

array([3, 3, 3, 3, 4, 5, 6, 6, 6, 6])

In [14]:
np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])

array([0, 5, 1, 2])

In [15]:
np.searchsorted([1,2,3,4,5], [1, 2, 5, 3])

array([0, 1, 4, 2])